#!/bin/bash
#
# If git isn't available on this system return
[ ! "$(type -P git)" ] && return

# Completion, has no dependencies
if [ -f "$HOME/.gitrc/git-completion" ]; then
    # This script is hundreds of lines long, and I felt it would be easier to keep it contained.
  . "$HOME/.gitrc/git-completion"
else
  >&2 echo "git-completion is not available!"
fi
